export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCESS = "CLEAR_ERROR_SUCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";
